# Generated by Django 5.2.1 on 2025-07-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_document_category_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
