# Generated by Django 5.2.1 on 2025-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_document_content_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('signed', 'Подписан'), ('rejected', 'Отклонен')], default='draft', max_length=20),
        ),
    ]
