# Generated by Django 5.2.1 on 2025-08-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='content',
        ),
    ]
