# Generated by Django 5.2.1 on 2025-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
