# Generated by Django 5.2.1 on 2025-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_school_email_school_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='headletter',
            field=models.FileField(blank=True, null=True, upload_to='headletters/'),
        ),
    ]
