# Generated by Django 5.2.1 on 2025-10-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exportbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
