# Generated by Django 5.2.1 on 2025-10-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_school_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportbook',
            options={'ordering': ['school', 'number']},
        ),
        migrations.RenameField(
            model_name='exportbook',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='exportbook',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
